services:
  client1:
    build:
      context: ./client
    volumes:
      - ./client/src:/app/src
    ports:
      - "8080:8080"
    depends_on:
      - websocket_api

  client2:
    build:
      context: ./client
    ports:
      - "8081:8080"
    depends_on:
      - websocket_api
    
  websocket_api:
    build: ./server
    command: uvicorn src.server:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./server/src:/app/src
    ports:
      - "8000:8000"

  