services:
  app:
    build: .
    command: flask --app ./src/hello --debug run --host=0.0.0.0 --port=8080
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
    
  
  db:
    image: mongo

